version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d

    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/config/:/mosquitto/config/
      - ./mqtt/data/:/mosquitto/data/
      - ./mqtt/log/:/mosquitto/log/
    networks:
      - backend
  
  mobius:
    build:
      context: ./mobius
    ports:
      - 7579:7579
    networks:
      - backend

  ai_module:
    build:
      context: ./ai_module
    ports:
      - 8080:80
    volumes:
      - ./ai_module:/ai_module
    networks:
      - backend

networks:
  backend:
